# Exploratory Data Analysis in SQL

Main Takeaways at the Bottom

Getting an Idea of what is included in the data frame.

In [14]:
df_18 = _deepnote_execute_sql('SELECT *\nFROM updated_data.csv', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_18

column0 InvoiceNo StockCode                          Description  \
0             0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1             1    536365     71053                  WHITE METAL LANTERN   
2             2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3             3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4             4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
...         ...       ...       ...                                  ...   
541904   541904    581587     22613          PACK OF 20 SPACEBOY NAPKINS   
541905   541905    581587     22899         CHILDREN'S APRON DOLLY GIRL    
541906   541906    581587     23254        CHILDRENS CUTLERY DOLLY GIRL    
541907   541907    581587     23255      CHILDRENS CUTLERY CIRCUS PARADE   
541908   541908    581587     22138        BAKING SET 9 PIECE RETROSPOT    

        Quantity      InvoiceDate  UnitPrice  CustomerID         Country  \
0              6   12/1/2010 8:26       2.55     17850.0  United Kingdom   
1              6   12/1/2010 8:26       3.39     17850.0  United Kingdom   
2              8   12/1/2010 8:26       2.75     17850.0  United Kingdom   
3              6   12/1/2010 8:26       3.39     17850.0  United Kingdom   
4              6   12/1/2010 8:26       3.39     17850.0  United Kingdom   
...          ...              ...        ...         ...             ...   
541904        12  12/9/2011 12:50       0.85     12680.0          France   
541905         6  12/9/2011 12:50       2.10     12680.0          France   
541906         4  12/9/2011 12:50       4.15     12680.0          France   
541907         4  12/9/2011 12:50       4.15     12680.0          France   
541908         3  12/9/2011 12:50       4.95     12680.0          France   

        New Value  
0       New Value  
1       New Value  
2       New Value  
3       New Value  
4       New Value  
...           ...  
541904  New Value  
541905  New Value  
541906  New Value  
541907  New Value  
541908  New Value  

[541909 rows x 10 columns]

In [34]:
df_1 = _deepnote_execute_sql('SELECT InvoiceNO, StockCode AS SKU, Description, Quantity, UnitPrice, CustomerID, country\nFROM updated_data.csv\n', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_1

InvoiceNo     SKU                          Description  Quantity  \
0         536365  85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1         536365   71053                  WHITE METAL LANTERN         6   
2         536365  84406B       CREAM CUPID HEARTS COAT HANGER         8   
3         536365  84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4         536365  84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
...          ...     ...                                  ...       ...   
541904    581587   22613          PACK OF 20 SPACEBOY NAPKINS        12   
541905    581587   22899         CHILDREN'S APRON DOLLY GIRL          6   
541906    581587   23254        CHILDRENS CUTLERY DOLLY GIRL          4   
541907    581587   23255      CHILDRENS CUTLERY CIRCUS PARADE         4   
541908    581587   22138        BAKING SET 9 PIECE RETROSPOT          3   

        UnitPrice  CustomerID         Country  
0            2.55     17850.0  United Kingdom  
1            3.39     17850.0  United Kingdom  
2            2.75     17850.0  United Kingdom  
3            3.39     17850.0  United Kingdom  
4            3.39     17850.0  United Kingdom  
...           ...         ...             ...  
541904       0.85     12680.0          France  
541905       2.10     12680.0          France  
541906       4.15     12680.0          France  
541907       4.15     12680.0          France  
541908       4.95     12680.0          France  

[541909 rows x 7 columns]

# Customer Analysis

What are the countries to which our customers reside?

In [56]:
df_2 = _deepnote_execute_sql('SELECT DISTINCT(country)\nFROM \'updated_data.csv\'', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_2

Country
0         United Kingdom
1                 France
2              Australia
3            Netherlands
4                Germany
5                 Norway
6                   EIRE
7            Switzerland
8                  Spain
9                 Poland
10              Portugal
11                 Italy
12               Belgium
13             Lithuania
14                 Japan
15               Iceland
16       Channel Islands
17               Denmark
18                Cyprus
19                Sweden
20               Austria
21                Israel
22               Finland
23               Bahrain
24                Greece
25             Hong Kong
26             Singapore
27               Lebanon
28  United Arab Emirates
29          Saudi Arabia
30        Czech Republic
31                Canada
32           Unspecified
33                Brazil
34                   USA
35    European Community
36                 Malta
37                   RSA

How many transactions in each country? 

In [37]:
df_3 = _deepnote_execute_sql('SELECT country, COUNT(DISTINCT(InvoiceNo)) as Count_of_Sales\nFROM \'updated_data.csv\'\nGROUP BY country;', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_3

Country  Count_of_Sales
0         United Kingdom           23494
1                Germany             603
2                 France             461
3                  Spain             105
4                 Sweden              46
5                   EIRE             360
6            Netherlands             101
7               Portugal              71
8            Switzerland              74
9        Channel Islands              33
10               Belgium             119
11             Australia              69
12                 Italy              55
13                Poland              24
14                Cyprus              20
15    European Community               5
16               Austria              19
17                 Malta              10
18                Greece               6
19             Singapore              10
20               Finland              48
21                 Japan              28
22                Norway              40
23               Denmark              21
24               Iceland               7
25                   USA               7
26                Israel               9
27        Czech Republic               5
28  United Arab Emirates               3
29               Bahrain               4
30                Brazil               1
31             Hong Kong              15
32          Saudi Arabia               2
33             Lithuania               4
34               Lebanon               1
35                Canada               6
36           Unspecified              13
37                   RSA               1

How many customers are there per country?

In [70]:
df_4 = _deepnote_execute_sql('SELECT country, COUNT(DISTINCT(CustomerID))\nFROM \'updated_data.csv\'\nGROUP BY country', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_4

Country  count(DISTINCT "CustomerID")
0         United Kingdom                          3951
1                 France                            88
2              Australia                             9
3            Netherlands                             9
4                Germany                            95
5                 Norway                            10
6                   EIRE                             4
7            Switzerland                            22
8                  Spain                            31
9                 Poland                             6
10              Portugal                            20
11                 Italy                            15
12               Belgium                            25
13             Lithuania                             1
14                 Japan                             8
15               Iceland                             1
16       Channel Islands                             9
17               Denmark                             9
18                Cyprus                             8
19                Sweden                             8
20               Austria                            11
21                Israel                             5
22               Finland                            12
23               Bahrain                             3
24             Hong Kong                             1
25               Lebanon                             1
26  United Arab Emirates                             2
27          Saudi Arabia                             1
28        Czech Republic                             1
29                Greece                             4
30                Canada                             4
31             Singapore                             1
32                   USA                             4
33                Brazil                             1
34           Unspecified                             5
35                 Malta                             2
36                   RSA                             1
37    European Community                             1

How many customers do we have in total?

In [73]:
df_6 = _deepnote_execute_sql('SELECT count(DISTINCT(CustomerID))\nFROM \'updated_data.csv\'', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_6

count(DISTINCT "CustomerID")
0                          4373

Top 10 Customers with the most orders

In [7]:
df_7 = _deepnote_execute_sql('SELECT DISTINCT CustomerID, SUM(Quantity) as Total_Quantity_Bought, Country\nFROM updated_data.csv\nGROUP BY CustomerID, Country\nLIMIT 10', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_7

CustomerID  Total_Quantity_Bought         Country
0     17850.0                   1693  United Kingdom
1     13047.0                   1355  United Kingdom
2     12583.0                   5009          France
3     13748.0                    439  United Kingdom
4     15100.0                     58  United Kingdom
5     15291.0                   2074  United Kingdom
6     14688.0                   3222  United Kingdom
7     17809.0                   2015  United Kingdom
8     15311.0                  37720  United Kingdom
9     14527.0                   2049  United Kingdom

In [ ]:
df_26 = _deepnote_execute_sql('--Top Customer by Sales Revenue\nSELECT CustomerID, ', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_26

What is the top 10 products for customer 17850?

In [20]:
df_16 = _deepnote_execute_sql('SELECT StockCode as SKU, Description,SUM(Quantity) as Quantity_Purchased\nFROM updated_data.csv\nWHERE CustomerID = 17850.0\nGROUP BY SKU, Description\nORDER BY Quantity_Purchased DESC\nLIMIT 10', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_16

SKU                          Description  Quantity_Purchased
0  85123A   WHITE HANGING HEART T-LIGHT HOLDER                 122
1   71053                  WHITE METAL LANTERN                 122
2  84029G  KNITTED UNION FLAG HOT WATER BOTTLE                 110
3  84406B       CREAM CUPID HEARTS COAT HANGER                 108
4   22633               HAND WARMER UNION JACK                 108
5   22632            HAND WARMER RED POLKA DOT                 108
6  84029E       RED WOOLLY HOTTIE WHITE HEART.                 104
7   21730    GLASS STAR FROSTED T-LIGHT HOLDER                 102
8   37370           RETRO COFFEE MUGS ASSORTED                  96
9   21068      VINTAGE BILLBOARD LOVE/HATE MUG                  96

Gross Sales to Each Customer (Top 10)

In [22]:
df_17 = _deepnote_execute_sql('SELECT CustomerID, ROUND(SUM(Quantity * UnitPrice), 2) AS Gross_Revenue\nFROM updated_data.csv\nWHERE CustomerID <> \'nan\'\nGROUP BY CustomerID\nORDER BY Gross_Revenue DESC\n', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_17

CustomerID  Gross_Revenue
0        14646.0      279489.02
1        18102.0      256438.49
2        17450.0      187482.17
3        14911.0      132572.62
4        12415.0      123725.45
...          ...            ...
4367     12503.0       -1126.00
4368     17603.0       -1165.30
4369     14213.0       -1192.20
4370     15369.0       -1592.49
4371     17448.0       -4287.63

[4372 rows x 2 columns]

# Product Analysis

Average Order Price? Average Unit Price? Average Order Quantity?

Gross Sales. Gross Sales by SKU

In [19]:
df_8 = _deepnote_execute_sql('--Gross Sales\nSELECT ROUND(SUM(Quantity * UnitPrice), 2) AS Gross_Revenue\nFROM updated_data.csv\n', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_8

Gross_Revenue
0     9747747.93

In [4]:
df_9 = _deepnote_execute_sql('--Gross Sales by SKU\nSELECT StockCode as SKU, Description, ROUND(SUM(Quantity * UnitPrice),2) AS Gross_Sales\nFROM updated_data.csv\nWHERE SKU <> \'DOT\'\nGROUP BY SKU, Description\nORDER BY Gross_Sales DESC\nLIMIT 10\n\n--Took out DOT as it is just the postage for each order. Same applies to the block below. ', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_9

SKU                         Description  Gross_Sales
0   22423            REGENCY CAKESTAND 3 TIER    164762.19
1   47566                       PARTY BUNTING     98302.98
2  85123A  WHITE HANGING HEART T-LIGHT HOLDER     97715.99
3  85099B             JUMBO BAG RED RETROSPOT     92356.03
4   23084                  RABBIT NIGHT LIGHT     66756.59
5    POST                             POSTAGE     66230.64
6   22086     PAPER CHAIN KIT 50'S CHRISTMAS      63791.94
7   84879       ASSORTED COLOUR BIRD ORNAMENT     58959.73
8   79321                       CHILLI LIGHTS     53768.06
9   23298                      SPOTTY BUNTING     42065.32

What are the top 10 selling products? In UK?

In [5]:
df_11 = _deepnote_execute_sql('SELECT StockCode as SKU, Description, ROUND(SUM(Quantity * UnitPrice),2) AS Gross_Sales\nFROM updated_data.csv\nWHERE Country = \'United Kingdom\' AND SKU <> \'DOT\'\nGROUP BY SKU, Description\nORDER by Gross_Sales DESC\nLIMIT 10', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_11

SKU                         Description  Gross_Sales
0   22423            REGENCY CAKESTAND 3 TIER    134405.94
1   47566                       PARTY BUNTING     92501.73
2  85123A  WHITE HANGING HEART T-LIGHT HOLDER     92000.59
3  85099B             JUMBO BAG RED RETROSPOT     84516.44
4   22086     PAPER CHAIN KIT 50'S CHRISTMAS      61888.19
5   84879       ASSORTED COLOUR BIRD ORNAMENT     54662.15
6   79321                       CHILLI LIGHTS     52986.86
7   22502      PICNIC BASKET WICKER 60 PIECES     39619.50
8   21137            BLACK RECORD COVER FRAME     39387.00
9   23084                  RABBIT NIGHT LIGHT     37894.16

Average Price Per SKU?

In [24]:
df_10 = _deepnote_execute_sql('SELECT StockCode as SKU, ROUND(AVG(UnitPrice), 2) as Average_Price\nFROM updated_data.csv\nGROUP BY SKU', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_10

SKU  Average_Price
0     85123A           3.10
1      71053           4.78
2     84406B           4.25
3     84029G           5.18
4     84029E           5.07
...      ...            ...
4065   23633           2.49
4066   22987           0.42
4067   23114           5.32
4068  90064B           3.75
4069   17174           0.42

[4070 rows x 2 columns]

Average Order Price

In [46]:
df_12 = _deepnote_execute_sql('SELECT ROUND(AVG(UnitPrice * Quantity), 2) as Order_Price\nFROM updated_data.csv\n', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_12

Order_Price
0        17.99

Average Unit Price

In [45]:
df_13 = _deepnote_execute_sql('-- Average Unit Price\nSELECT ROUND(AVG(UnitPrice), 2) as Price\nFROM updated_data.csv', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_13

Price
0   4.61

Average Order Quantity

In [44]:
df_14 = _deepnote_execute_sql('-- Average Quantity Amount\nSELECT ROUND(AVG(Quantity), 2) as Quantity\nFROM updated_data.csv', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_14

Quantity
0      9.55

In [12]:
df_14 = _deepnote_execute_sql('SELECT DISTINCT(StockCode) as SKU, Description, ROUND(AVG(UnitPrice), 2) as Average_Price\nFROM updated_data.csv\nGROUP BY SKU, Description\nORDER BY Average_Price DESC', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_14

SKU                     Description  Average_Price
0     AMAZONFEE                      AMAZON FEE        7324.78
1         22502  PICNIC BASKET WICKER 60 PIECES         649.50
2          CRUK                 CRUK Commission         495.84
3             M                          Manual         375.57
4           DOT                  DOTCOM POSTAGE         290.91
...         ...                             ...            ...
5747      35653                            None           0.00
5748      21294                            None           0.00
5749      37327                      adjustment           0.00
5750     84857B                            None           0.00
5751          B                 Adjust bad debt       -3687.35

[5752 rows x 3 columns]

The block above includes some records that I do not want to factor in, therefore I will exclude them in the next block to get a true sense of the highest average priced items. 

In [18]:
df_15 = _deepnote_execute_sql('SELECT DISTINCT(StockCode) as SKU, Description, ROUND(AVG(UnitPrice), 2) as Average_Price\nFROM updated_data.csv\nWHERE  SKU NOT IN (\'AMAZONFEE\', 22502, \'CRUK\', \'M\', \'DOT\', \'BANK CHARGES\')\nGROUP BY SKU, Description\nORDER BY Average_Price DESC\nLIMIT 10', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_15

SKU                         Description  Average_Price
0  22828        REGENCY MIRROR WITH SHUTTERS         156.43
1  22827  RUSTIC  SEVENTEEN DRAWER SIDEBOARD         156.03
2  22655         VINTAGE RED KITCHEN CABINET         150.66
3  22656        VINTAGE BLUE KITCHEN CABINET         143.65
4  22823       CHEST NATURAL WOOD 20 DRAWERS         118.08
5  22826       LOVE SEAT ANTIQUE WHITE METAL         115.39
6  22016  Dotcomgiftshop Gift Voucher 100.00          83.33
7      D                            Discount          72.48
8  21769         VINTAGE POST OFFICE CABINET          66.36
9  22929              SCHOOL DESK AND CHAIR           64.06

# Time Series Analysis

Firstly we need to clean the data to be in the correct format and we need to extract information from the InvoiceDate column. 

In [36]:
df_19 = _deepnote_execute_sql('--Allows me to see the format of the Date. \nSELECT InvoiceDate\nFROM updated_data.csv\nLIMIT 1\n\n--I will need to work around this format to get the month and the actual day', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_19

InvoiceDate
0  12/1/2010 8:26

Used python to add the day, month, year columns to our data frame. Will use SQL below to analyze. 

In [45]:
import pandas as pd

df = pd.read_csv('updated_data.csv')

df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'], format='%m/%d/%Y %H:%M')

df['Month'] = df['InvoiceDate'].dt.month
df['Day'] = df['InvoiceDate'].dt.day
df['Year'] = df['InvoiceDate'].dt.year

df.to_csv('updated_data_timeseries.csv', index=False)
df.head()

Unnamed: 0 InvoiceNo StockCode                          Description  \
0           0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1           1    536365     71053                  WHITE METAL LANTERN   
2           2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3           3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4           4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   

   Quantity         InvoiceDate  UnitPrice  CustomerID         Country  \
0         6 2010-12-01 08:26:00       2.55     17850.0  United Kingdom   
1         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   
2         8 2010-12-01 08:26:00       2.75     17850.0  United Kingdom   
3         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   
4         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   

   New Value  Month  Day  Year  
0  New Value     12    1  2010  
1  New Value     12    1  2010  
2  New Value     12    1  2010  
3  New Value     12    1  2010  
4  New Value     12    1  2010

In [46]:
df_20 = _deepnote_execute_sql('-- Viewing a sample of the new dataframe. \nSELECT *\nFROM updated_data_timeseries.csv\nLIMIT 10', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_20

Unnamed: 0 InvoiceNo StockCode                          Description  \
0           0    536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER   
1           1    536365     71053                  WHITE METAL LANTERN   
2           2    536365    84406B       CREAM CUPID HEARTS COAT HANGER   
3           3    536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE   
4           4    536365    84029E       RED WOOLLY HOTTIE WHITE HEART.   
5           5    536365     22752         SET 7 BABUSHKA NESTING BOXES   
6           6    536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER   
7           7    536366     22633               HAND WARMER UNION JACK   
8           8    536366     22632            HAND WARMER RED POLKA DOT   
9           9    536367     84879        ASSORTED COLOUR BIRD ORNAMENT   

   Quantity         InvoiceDate  UnitPrice  CustomerID         Country  \
0         6 2010-12-01 08:26:00       2.55     17850.0  United Kingdom   
1         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   
2         8 2010-12-01 08:26:00       2.75     17850.0  United Kingdom   
3         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   
4         6 2010-12-01 08:26:00       3.39     17850.0  United Kingdom   
5         2 2010-12-01 08:26:00       7.65     17850.0  United Kingdom   
6         6 2010-12-01 08:26:00       4.25     17850.0  United Kingdom   
7         6 2010-12-01 08:28:00       1.85     17850.0  United Kingdom   
8         6 2010-12-01 08:28:00       1.85     17850.0  United Kingdom   
9        32 2010-12-01 08:34:00       1.69     13047.0  United Kingdom   

   New Value  Month  Day  Year  
0  New Value     12    1  2010  
1  New Value     12    1  2010  
2  New Value     12    1  2010  
3  New Value     12    1  2010  
4  New Value     12    1  2010  
5  New Value     12    1  2010  
6  New Value     12    1  2010  
7  New Value     12    1  2010  
8  New Value     12    1  2010  
9  New Value     12    1  2010

In [47]:
df_21 = _deepnote_execute_sql('-- Shows us the distinct months, days, and years as needed. Used this for data validation. \n\n--SELECT DISTINCT (month)\n--FROM updated_data_timeseries.csv\n\n--SELECT DISTINCT (year)\n--FROM updated_data_timeseries.csv\n\n--SELECT DISTINCT (day)\n--FROM updated_data_timeseries.csv\n\n', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_21

Year
0  2010
1  2011

Time EDA

Sales per Year

In [54]:
df_24 = _deepnote_execute_sql('SELECT DISTINCT(year) as Year, COUNT(DISTINCT(InvoiceNo))\nFROM updated_data_timeseries.csv\nGROUP BY Year\nORDER BY Year ASC\n\n-- Interesting disperity in the data as far as the difference in Invoices between the two years.\n-- Will need to investigate it further. ', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_24

Year  count(DISTINCT "InvoiceNo")
0  2010                         2025
1  2011                        23875

In [5]:
df_25 = _deepnote_execute_sql('--Investigating further in the invoice disperity\nSELECT DISTINCT month\nFROM updated_data_timeseries.csv\nWHERE year = 2010\n\n-- There is only December for 2010. We will need to exclude or sperate it.', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_25

Month
0     12

Gross Revenue per Year

In [3]:
df_23 = _deepnote_execute_sql('SELECT DISTINCT(year) as Year, ROUND(SUM(UnitPrice * Quantity), 2) AS Gross_Sales\nFROM updated_data_timeseries.csv\nWHERE year = 2011\nGROUP BY Year\nORDER BY Year ASC\n\n-- Only looking at 2011 as there is only one month of data for 2010. ', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_23

Year  Gross_Sales
0  2011   8998790.91

Gross Revenue per Month over the two years. 

In [12]:
df_22 = _deepnote_execute_sql('SELECT DISTINCT(month) as Month, ROUND(SUM(UnitPrice * Quantity), 2) AS Gross_Revenue\nFROM updated_data_timeseries.csv\nWHERE year = 2011\nGROUP BY Month\nORDER BY Gross_Revenue DESC\n\n-- Looks like November is best month for revenue in 2011. ', 'SQL_DEEPNOTE_DATAFRAME_SQL')
df_22

Month  Gross_Revenue
0      11     1461756.25
1      10     1070704.67
2       9     1019687.62
3       5      723333.51
4       6      691123.12
5       3      683267.08
6       8      682680.51
7       7      681300.11
8       1      560000.26
9       2      498062.65
10      4      493207.12
11     12      433668.01

# Main Takeaways

- We sell to 38 countries
- UK has the highest count of customers at 3,951 out of 4,373 total customers.
- While Customer 17850 has ordered the most product by quantity, customer 14646 has contributed to the most amount of revenue at $279,489.02 out of a total of $9,747,747.93 in the 13 months observed. 
- Our average order price is $17.99, the average unit price is $4.61, and the average quantity ordered is 9.55 units. 
- For 2011, the best month by revenue was November at $1,461,756.25. 

<a style='text-decoration:none;line-height:16px;display:flex;color:#5B5B62;padding:10px;justify-content:end;' href='https://deepnote.com?utm_source=created-in-deepnote-cell&projectId=a35bdb4e-7a4b-4897-9fbe-64f7703ba45a' target="_blank">
 </img>
Created in <span style='font-weight:600;margin-left:4px;'>Deepnote</span></a>